### ISSUE TITLE
[Bug]: todo-list-example 无法正常 bundle, deploy

### ISSUE THREAD

**Issue by skypesky** [blocklet/create-blocklet#323]
- [ ] 可以参考 https://github.com/blocklet/ai-todo-list 进行改进, see https://arcblock.slack.com/archives/D03A04Y4TND/p1716795648424989
- [ ] 用户没有登陆，console 会报错

![image](https://github.com/blocklet/create-blocklet/assets/33124160/c6e00d24-08fa-4717-a392-ae9017ad9116)

- [ ] 确保 bundle 没有错误
- [ ] 使用 rest api

**Comment by LancelotLewis** [comment]
新版已支持 bundle, deploy
